- public/index.html
YOLO commit for data common whale
> Try fixing script host

- public/.gitignore
- public/app/components/CommunityProfiles.jsx
- public/app/components/visualizations/LineChart.jsx
- public/app/containers/visualizations/LineChart.js
- public/package.json
- public/yarn.lock
Almost addresses #91. This chart is still missing labels and the legend isn't styled.
We need a line chart.
> Partial line chart for demo

- public/app/actions/chart.js
- public/app/components/CommunityProfiles.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/app/constants/charts.js
- public/app/constants/locations.js
- public/app/utils/charts.js
- public/assets/styles/modules/chart.scss
Resolves #123.
We needed the school enrollment chart for multiple school districts.
> Complex school enrollment chart

- public/app/actions/chart.js
- public/app/components/CommunityProfiles.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/app/constants/charts.js
- public/app/constants/locations.js
- public/app/utils/charts.js
- public/assets/styles/modules/chart.scss
Resolves #124.
This is our sixth chart.
> Educational attainment by race chart

- public/app/actions/chart.js
- public/app/components/CommunityProfiles.jsx
- public/app/components/visualizations/ChartDetails.jsx
- public/app/components/visualizations/LineChart.jsx
- public/app/components/visualizations/PieChart.jsx
- public/app/components/visualizations/StackedAreaChart.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/app/constants/charts.js
- public/app/constants/locations.js
- public/app/containers/visualizations/LineChart.js
- public/app/containers/visualizations/PieChart.js
- public/app/utils/charts.js
- public/assets/styles/modules/chart.scss
Resolves #125, resolves #126, resolves #127, resolves #128, resolves #129, resolves #130, resolves #131, resolves #132, resolves #133.
We really needed to finish all of the charts ASAP.
> Final chart push

- public/app/components/CommunityProfiles.jsx
- public/app/components/visualizations/LineChart.jsx
- public/app/components/visualizations/PieChart.jsx
- public/app/components/visualizations/StackedAreaChart.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/app/utils/charts.js
- public/assets/styles/components/CommunityProfiles.scss
- public/assets/styles/components/Tab.scss
- public/assets/styles/modules/chart.scss
- public/assets/styles/modules/container.scss
- public/assets/styles/modules/header.scss
- public/assets/styles/partials/_mixins.scss
Resolves #82.
Print styling must be at least somewhat elegant.
> First pass at print styling

- public/app/components/CommunityProfiles.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/app/constants/charts.js
Jay thought the stacked area chart could be misleading since we're dropping years for which we don't have the data.
> Switch housing permitted chart to stacked bar graph

- public/app/components/Home.jsx
- public/app/components/partials/Header.jsx
- public/assets/styles/modules/header.scss
Resolves #109.
Navigation was not mobile responsive.
> Implement horizontal scrolling for mobile navigation

- public/app/components/CommunityProfiles.jsx
- public/app/components/MunicipalityPolygon.jsx
- public/app/components/partials/Header.jsx
- public/app/components/visualizations/ChartDetails.jsx
- public/app/components/visualizations/LineChart.jsx
- public/app/components/visualizations/PieChart.jsx
- public/app/components/visualizations/StackedAreaChart.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/app/constants/charts.js
- public/app/constants/colors.js
- public/app/utils/charts.js
- public/assets/styles/components/CommunityProfiles.scss
- public/assets/styles/components/Tab.scss
- public/assets/styles/modules/chart.scss
- public/assets/styles/modules/header.scss
Resolves #165. Resolves #159. Resolves #163.
People had feelings about the community profiles page.
> All of the styling changes

- app/shapefile.rb
Allow download of shapefiles from the towndata database.
Depends on MAPC/databrowser#20
Resolves #173.
> Resolve #173 Towndata Download

- app/shapefile.rb
> Fix Shapefile Download Link

- app/csv.rb
- app/shapefile.rb
- public/assets/styles/modules/header.scss
> Merge Staging Updates into Master

- public/app/reducers/dataset.js
> Fix search dataset id

- public/app/components/App.jsx
- public/app/components/partials/Header.jsx
- public/app/components/visualizations/ChartDetails.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/yarn.lock
Resolves #196.
We should highlight the header link the same way that the Browser highlights the Browser link when in that part of the website.
It emboldens the link the same way that DataBrowser does
This issue also addresses a few console errors that were occurring. There may be possible performance improvements from these changes, but it definitely saves us ~150 console errors.
> Community Profile links highlight

- public/app/components/App.jsx
- public/app/components/partials/Header.jsx
- public/app/components/visualizations/ChartDetails.jsx
- public/app/components/visualizations/StackedBarChart.jsx
- public/assets/styles/routes/datasets.scss
- public/yarn.lock
Resolves #192 .
The back button was obfuscated by the table header meta info.
It adds the link back into the document flow, pushing the table meta header down as much as necessary.
None
> Browser back link

- app/javascript/pages/assets/data/temp-cal-data.json
- app/javascript/pages/components/Calendar.jsx
* Add two-digit-industry-group-01-17.csv
* Update all JSON data for calendars 2015-2020
* Edit Calendar.jsx to point to the two-digit csv  file
> Update JSON data and add two-digit csv file

- app/javascript/pages/components/Gallery.jsx
- app/javascript/pages/components/Home.jsx
- app/javascript/styles/components/Spotlights.scss
#Why is this change necessary?
- Adds the hover effect on the calendar as seen in the XD
- Fixes button font styling issue (was being styled as h3; should be styled as h4)
- Insert new copy on gallery and homepage
Put the image in a wrapper with another div, then show that semi-transparent div on hover.
None
> Add calendar hover effect and new text

- app/javascript/pages/components/Gallery.jsx
I got the updated copy from Jessie, but didn't want to singlehandedly mess with /dev since we're kind of mid-deployment.
> Update copy on Gallery page

- app/javascript/pages/components/Gallery.jsx
- app/javascript/pages/components/Home.jsx
> Fix minor copy typos

- app/javascript/pages/store.js
- package.json
- yarn.lock
This commit adds Google Analytics to the app using the react-ga library and does so by connecting it to the Redux store.
> Add Google Analytics

- app/javascript/pages/components/DataViewer.jsx
This commit changes the request to PRQL to use a token based off the database it is requesting from. It also DRYs up some of the queries.
> Fix PRQL Token

- app/javascript/pages/components/partials/DatasetHeader.jsx
* This commit adds event tracking triggers to dataset downloads for CSV and shapefiles so we can get a sense of what datasets folks are downloading.
* Also applies prettier.js formatting to the JSX file.
> Resolve #218 Add Event Tracking to Dataset Downloads

- config/deploy.rb
- config/deploy/staging.rb
* Since we use nvm the same way on staging and production this commit migrates those changes to deploy.rb.
> Migrate nvm settings

- app/javascript/pages/components/partials/DataMenu.jsx
In order to show the correct dataset count we feed the child items object to datasetCount and then update it to inspect the length.
> Resolve #354 Dataset Count

- app/javascript/pages/components/gallery/2020/December.jsx
- app/javascript/styles/components/Calendar.scss
* Add date and citation for December.
> Update December w/Citation

- .gitignore
- app/javascript/pages/components/Home.jsx
- app/javascript/pages/components/gallery/CalendarGrid.jsx
Resolves # .
Updates landing by removing the calendar graphic.
> Update to landing
