app/sync_tabular_data_with_carto.rb
This commit removes the now working table supressions that were tested as part of #54. We still supress data_browser because that is a meta table and the means_by_traveltime_to_work_acs_bg because we do not know why that table is failing to sync. However all the other tables sync’d correctly with a manual POST sync request.
=> Remove Table Sync Supressions

public/assets/styles/routes/datasets.scss
This commit cleans up the metadata style for the data browser.
It was suggested by @ericyoungberg in https://github.com/MAPC/databrowser/pull/8#issuecomment-410729303 in order to improve the display of metadata.
It makes it so that the metadata is better formatted.
=> Update Metadata Style

app/shapefile.rb
In our refactoring of DataBrowser for PRQL we added the table schema to requests data browser sends. Unfortunately the shapefile endpoint was not updated to reflect this. This commit updates the command to properly point to the right table and schema based on the request from databrowser.
=> Update Shapefile Endpoint for PRQL

public/app/actions/dataset.js
I broke the dataset count when I generalized the locations.BROWSER_API to require a specific token to be specified.
=> Fix dataset count

public/index.html
Resolves #40.
We want to know who goes to the page.
**How does it address the issue?**
This is just a copy-paste of the databrowser Google Analytics. It does not integrate with react router at this time.
=> Simple version of Google Analytics

datacommon.sublime-project, public/app/actions/dataset.js
This commit fixes the dataset count on the front page to match what is seen in the Databrowser portion of the app.
It also adds some node related folders to the sublime project file so they are helpfully ignored when searching.
Resolves #134.
=> Resolve #134 Fix dataset count

public/app/constants/charts.js
In the housing units permitted chart, we need to differentiate between years with 0 permitted units and years we're ignoring because not all 12 months were reported.
=> Mark ignored columns in housing units permitted chart for clarity

app/town_metadata.rb, config.ru, config/settings.yml
This commit adds an endpoint to allow for the summoning of metadata in the towndata database.
* Refactor endpoint names to correspond to database names instead of schemas
* This will break databrowser until it is updated to reflect the new convention
* Because the names of the tables in the metadata table start with a capital letter we must downcase it in the code to achieve a match.
* End users will need to set database information in settings.yml
=> Add TownData Endpoint

Gemfile, Gemfile.lock, README.md, app/csv.rb, app/shapefile.rb, config.ru
Resolves #170.
Users would like to download CSV files and the move to PRQL has removed this feature.
It adds an endpoint to data common to allow for CSV downloads of datasets
None.
=> Resolve #170 Add CSV Endpoint

public/app/components/visualizations/LineChart.jsx, public/app/constants/charts.js
Resolves #164 .
Hull, Chatham, and Provincetown entirely crash the page because we don't have certain data on those communities.
**How does it address the issue?**
This PR adds input validation on formatting functions, and prevents null values for water usage chart.
=> Fix entirely crashing communities

public/.babelrc, public/app/components/MapBox.jsx, public/app/components/visualizations/StackedBarChart.jsx, public/app/constants/charts.js, public/app/index.jsx, public/package.json, public/yarn.lock
Resolves #169. Resolves #175.
Lock map and add babel-polyfill for IE.
=> Lock map and add babel-polyfill

README.md, config/deploy/production.rb, lib/capistrano/tasks/compile_react.rake, public/package.json
Add and update scripts to deploy to production.
So we can deploy to production.
Adding a note in the README.md about our caching of PRQL to warn future generations of the caching issues they may face, and then adding scripts to push to production.
🚀
=> Add production deployment scripts

public/assets/styles/routes/categories.scss
Resolves #190 . Implemented by https://github.com/MAPC/databrowser/pull/25
Long category titles in the category list panels of Browser would cause the dataset count within those categories to be displaced downwards. 
Implements a flex structure that allows the category title and dataset count to share the space
None
=> Implement flex columns on category lists in Browser

.gitignore, Dockerfile, Rakefile, app/csv.rb, app/shapefile.rb, lib/tasks/generate_cache.rb, package.json
Resolves #193.
The original intent of the download was that the browser should only be downloading data by the selectable year filters on the site. 
It checks for year values before resolving the query arguments. If the `years` and `year_col` params exist, then the data will be filtered by years selected.
The results of a year query are stored in the warmed cache.
=> Download selected years

public/assets/styles/partials/_base.scss
Resolves #205 .
It doesn't look like it should in IE
It expands the height of the main app window to expand to height of browser window.
=> Fix the DataBrowser's main app window flex height

app/javascript/pages/components/partials/BlankCalendarItem.jsx, app/javascript/pages/components/partials/CalendarGrid.jsx, app/javascript/styles/components/Calendar.scss
Resolves # .
We needed the full 4x3 grid of calendar items to maintain visual balance in the app and make it clear that this is similar to an advent calendar in function. However, because we want to keep each data story secret before its first-of-the-month release, we needed some new sort of blank box to fill space.
Styles a new component, BlankCalendarItem (similar to the regular CalendarItem), to show a blank green box and then show "Coming Soon" on hover.
No side effects, but we may need to adjust this solution slightly when we start reading in the proper backend API.
=> Create temporary blank boxes for 2020

app/javascript/pages/components/Gallery.jsx
Update the "Sign Up" link to point to Constant Contact instead of the homepage
=> Update sign-up link for Constant Contact

app/javascript/pages/components/Calendar.jsx
Resolves #240 .
With the industry titles off to the right side of each bar, having the axes layer over the text was breaking some of the illusion of the race, resulting in an awkward user experience.
Moved the function call `labels` after the call to `axis` so that the text would be drawn onto the SVG on top of the axes, no CSS required.
None; the two functions work independently of one another.
=> Change SVG draw order so text goes on top of axes

app/javascript/pages/components/Home.jsx, app/javascript/styles/components/Spotlights.scss
Resolves #233 .
Kit and I previously discussed the margins on the homepage and how to get as much standardization in as possible, and she suggested using the "Data by category" section as the standard. Implementing that on "Community Profiles" will be a bit tricky due to absolute positioning, but implementing it for "Gallery of Data" just required a little bit of margin manipulation to create the indented look of the text.
Set the default margins to match the category grid and then set negative margins on the title.
It shouldn't have any, but I could see something coming up when we swap out the tall poster image for the longer bar chart race screenshot.
=> Standardize margins of top two homepage sections

app/javascript/pages/components/Gallery.jsx, app/javascript/pages/components/partials/CalendarGrid.jsx, app/javascript/styles/components/Calendar.scss, app/javascript/styles/components/Spotlights.scss
Resolves #237 .
The size of the grid cells was tied to the size of the screen, resulting the calendar boxes to look either stretched or squished depending on the browser size.
I set an absolute size for the boxes and a `max-width` for the grid itself that is equal to the widths of the squares plus their column margins. Then, I horizontally centered the grid so that there would be equal margins on either side.
Once the medium screen breakpoint is hit (960px)/the layout goes to two columns, the leftmost image is shorter than the rightmost text, which we tried to avoid:
However, this doesn't seem to impact mobile (everything is just scaled down and shows in a 3-column layout). Fixing this would require either reworking the box sizes at various breakpoints or having inconsistent margins at …
=> Standardize calendar box sizes at 250px

app/javascript/pages/components/Calendar.jsx
The labels (axis and bar) were previously quite small at 100% zoom, which made them hard to read. They also were not in the default font of the side (Montserrat light, 16px).
Updated the font family and changed the font sizes proportionally.
There are two things that stick out to me:
1) On regular view, the bar labels seem to match the paragraph text fine size-wise. However, when Dev Tools is open on Chrome, the font size increases:
This must be related to a behavior I noticed wherein declaring 16px for the SVG's `font-size` attribute didn't equal 16px on a regular CSS-styled bit of text. When Dev Tools is closed and the page refreshed, things go back to normal. 
2) When I changed the font to Montserrat, the contrast between the light and bold versions was so great that having bold …
=> Increase font sizes for graph text

app/javascript/pages/components/Home.jsx, app/javascript/styles/components/Spotlights.scss
Resolves # .
Image for January 2020 data viz was outdated.
Image for January 2020 data viz was outdated.
* Point default and background images to updated screenshots
* Set width to prevent text jumping
None
=> Change images to reflect latest

app/javascript/pages/components/App.jsx, app/javascript/pages/components/Browser.jsx, app/javascript/pages/components/partials/DataMenu.jsx, config/routes.rb
In order for the front page to be able to link to a cageory of datasets, we needed to add a feature to set state based on the URL. This commit accomplishes that goal by adding a route to capture the url segement the Ember application used to display the menu, and then set the state for the first menu selection based on that value.
=> Add Working URL Routes

app/javascript/pages/components/DataViewer.jsx, app/javascript/pages/components/partials/DatasetTable.jsx
This commit fixes the column ordering by summoning the order of columns from the relevant metadata and then mapping it to the actual columns available from the dataset.
=> Resolve #257 Fix Column Ordering

app/javascript/styles/routes/datasets.scss
* Remove width: 50% to allow natural spreading and wrapping of the year filter buttons, and prevent weird vertical stacking on mobile.
* Refactor class to follow sass-lint suggestions.
=> Fix Year Filter Wrap on Mobile

app/javascript/pages/components/Calendar.jsx, app/javascript/styles/components/Calendar.scss, app/javascript/styles/partials/_base.scss
Resolves # .
The bar chart was not working well on mobile devices.
This makes it scale the bar chart race at mobile sizes.
Some frustrating CSS was evicted or modified to make the updates to the chart subtitle easier. A quick check of the rest of the site didn't seem to indicate that the rules had impact on it, but its possible something somewhere is a little bit different due to them. If the impact is not material I'd recommend making separate issues for those as we continue to refactor this to follow BEM conventions.
=> Responsive Bar Chart Race

app/javascript/pages/components/calendar-visualizations/2020/February.jsx, app/javascript/styles/components/Calendar.scss
* We needed to update the legend of the map with study area boundary to include boundary key. This changed the height of the legend. In order to keep consistent breakpoints throughout, we needed to adjust the heights of both legends.
We needed to increase the size of the legend to accommodate another legend item on the Map With Boundary version that appears on DataCommon. Because both that map and the map here rely on the same media queries in the Large Units repo, this legend needed to be updated correspondingly. Additionally, we needed to update link text to correspond with the correct bitly.
Increase height variable to use in media queries
None; the variable is referenced in a couple of media queries to move the position of the legend. As for the link update, the anchor tag hasn't …
=> Update bitly link and legend height

app/javascript/pages/index.jsx, package.json, yarn.lock
Currently, only the DataBrowser was accessible on IE11. Given that some of our users historically use IE11, it is important for us to make the entire site accessible on that browser.
Adding the [react-app-polyfill](https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill) package adds the proper polyfills to compile our JavaScript into an earlier, IE11-digestible version.
Although this now allows users to visit the full DataCommon site on IE11, it also brought to life multiple issues with design and performance on that browser (such as the newly-installed grid for the calendar and the ability to compile and download metadata). These individual instances are being documented and will be addressed in several future pull requests.
=> Add react-app-polyfill for IE11 compatibility

app/javascript/pages/components/partials/Particles.jsx, app/javascript/styles/components/Particles.scss
Resolves #284 .
On some renderings of the Particles component, the height was off. This resulted in the canvas elements appearing distorted and the sliced triangle taking up too much space.
- Determine the exact height and width based on innerWidth and, additively, how much space the font + padding takes
- Assign this value for both the canvas height/width attributes (how many pixels should go into the element) and the height/width style (how many pixels that space should take up); this mismatch was causing the distortion
I took this as an opportunity to refactor the random number generator so that dots always stayed within the bounds of the canvas. Now, the dots don't all seem to disappear after a minute.
=> Match exact counts for height/width on styling and element attribute

app/assets/data/march2020.csv, app/javascript/pages/components/gallery/2020/March.jsx
After a month or so, we wanted to remove the dynamic API call to MassBuilds and instead refer to a static CSV file (pulled today at 11:15AM)
- Remove API call and edit d3 code to accommodate new data source
- Double-checked data numbers to ensure we were pulling the correct specifications of developments (MAPC region with a `year_compl` value between 2015 - 2025)
I noticed two things when getting to work on this; because they occurred before I swapped data sources, I'm making two new issues.
1) Tooltip moves slightly, but mostly stays in the top left corner of the map (probably a CSS issue)
2) Sometimes, the CSV data is ready to go before the base map is. In these cases, the first year of data loads underneath the MAPC region. I tried resolving this with a timeout but it doesn't seem to …
=> Replace March API call with static spreadsheet

app/javascript/pages/components/gallery/2020/January.jsx, package.json, yarn.lock
A few `for...of` loops in the [d3-array](https://github.com/d3/d3-array) package weren't getting transpiled with Babel, resulting in the entire DataCommon site to not display in IE11.
As I note in the commit history, this ideally would have been resolved with edits to the Babel and Webpack config (perhaps some Regex excluding all node modules but d3-array?). However, they just never connected. After several days of attempts, I resolved this by implementing the necessary d3 functions directly in the January class file (the polyfill works fine for non-node-module code).
I removed the d3-array package from the package.json to keep things as clean as possible.
=> Add necessary d3-array functions directly into January class

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/application.rb
* Setup Sentry with relevant configuration and settings to catch and transmit exceptions.
Resolves #41  .
We want to track errors and exceptions in Sentry.
It adds the gem and relevant configuration.
=> Setup Sentry

app/javascript/pages/components/partials/DatasetHeader.jsx
* Fix typo of key name to populate column labels (or should I say labls) in metadata download.
=> Resolve #250 Geospatial Metadata Download

app/javascript/pages/constants/charts.js
Resolves #351 (somewhat) .
Some community profile charts were displaying out-of-date information or incorrect labels (say, they were pulling 2018 data but the axis suggested it was 2016 data)
I manually went through the `/constants/charts.js` file and checked each chart's data source to see if there was new data we should be referencing. This mostly involved just updating labels, but did require updating a couple references to `acs_year` so that the correct data would come through.
This doesn't automate things so much as keep them up-to-date as of now. I wrote a little more in the issue itself, but I think that examining and implementing automation for both the data and the labels would take vastly more time than occasionally checking the charts and updating values as they come up. If we …
=> Adjust dates for community profile charts

app/javascript/pages/components/App.jsx, app/javascript/pages/components/Browser.jsx, config/routes.rb
* Update routes to allow for one or two params in the URL to display datasets.
* Update state code to push clicks of menu items into the router history so that they will display in the URL.
* Update the function calls inside onMenuClick inside arrow functions so that they are only called when clicked, not when the page is loaded.
* Remove dead code: history import.
* Update constructor to set menuTwoSelectedItem from the URL params so that direct links will display a page with the correct datasets displayed.
* Remove outdated comment: some of the code in DataViewer component is still coupled to this method of changing what page is displayed so we cannot currently use history.push.
=> Resolve #357 Dataset Link History

app/javascript/pages/components/partials/DatasetHeader.jsx
* Because the Zoning Atlas data did not properly display for users who chose to use Excel as their CSV viewer, we are now providing a Sharepoint link that is in XLSX format for their conveinence.
* Even more annoying was that the shapefile did not include any shapes when we exported it. So we also had to create the shapefile manually and put into sharefile.
Related to #366 and #365, but does not fix them beyond Zoning Atlas.
=> Hotfix for Zoning Atlas Data

app/javascript/pages/components/gallery/2020/April.jsx, app/javascript/pages/components/gallery/2020/December.jsx, app/javascript/pages/components/gallery/2021/January.jsx
Resolves #368 .
For some reason, Chrome users sometimes view only partially-loaded maps, or the height maxes out at 300px instead of reaching the expected 500px.
After the map loads, a `resize` event is fired/ Because the rest of the DOM is set, the map should now fill its proper space. To test, go to each map page on Chrome, then hard refresh, then regular refresh; the map should load normally in all 3 scenarios.
Users with an initially-partially-loaded map will briefly notice the resize.
=> Add map resize calls to April 2020, December 2020, January 2021

.gitignore, app/javascript/pages/components/Home.jsx, app/javascript/pages/components/gallery/CalendarGrid.jsx
Resolves #400  .
This removes the 2021 calendar image from the home page, which highlighted our backlog of calendar viz's.
=> Remove calendar from landing and blank months from gallery
